services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/bash
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/workspace
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/workspace
      - /workspace/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true


volumes:
  mysql_data:
  node_modules_volume:
